In [1]:
import numpy as np

#Creating a numpy array
myarr = np.array([[1, 2, 3, 4, 5]], np.int8)

#Accessing individual elements
print(f"Accessing : {myarr[0, 1]}\n")

#details on the array
print(f"Shape of array : {myarr.shape}\n")
print(f"Data type : {myarr.dtype}\n")
print(f"INDEX of max element : {myarr.argmax()}\n")
print(f"INDEX of min element : {myarr.argmin()}\n")
print(f"sorted array INDICES : {myarr.argsort()}\n")

Accessing : 2

Shape of array : (1, 5)

Data type : int8

INDEX of max element : 4

INDEX of min element : 0

sorted array INDICES : [[0 1 2 3 4]]



In [2]:
#Array creation by Conversion from other Python structures
listarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], np.int8)
print(f"2-D array : \n{listarray}")

objectarray = np.array({32, 23, 55})
print(f"\nObject type array : {objectarray} \n\nData Type : {objectarray.dtype}")

2-D array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Object type array : {32, 23, 55} 

Data Type : object


In [3]:
#Array creation using "Zeros"
zeros = np.zeros((2, 5))
print(f"Zeros : \n{zeros}")
print(f"Data Type : {zeros.dtype}")
print(f"Shape : {zeros.shape}\n")

#Array creation using "arange"
rng = np.arange(10)
print(f"Arange : {rng}\n")

#Array creation using "linspace"
lspace = np.linspace(1, 5, 12)
print(f"Linspace : \n{lspace} \n")

#Empty array of given dimensions
emp = np.empty((4, 6))
print(f"Empty : \n{emp} \n")

#Identity Matrix
ide = np.identity(5)
print(f"Identity Matrix : \n{ide}")

Zeros : 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Data Type : float64
Shape : (2, 5)

Arange : [0 1 2 3 4 5 6 7 8 9]

Linspace : 
[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ] 

Empty : 
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.11260755e-306
  1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 1.37962320e-306 1.29060871e-306
  2.22518251e-306 1.33511969e-306]
 [1.78022342e-306 1.05700345e-307 3.11525958e-307 1.69118108e-306
  8.06632139e-308 1.20160711e-306]
 [1.69119330e-306 1.29062229e-306 6.89804133e-307 9.34609790e-307
  9.34609790e-307 1.60219035e-306]] 

Identity Matrix : 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
#Creating array using "arange"
arr = np.arange(99)
print(f"Arange \n{arr}\n")

#Changing shape/dimensions
arr = arr.reshape(3, 33)
print(f"Reshape \n{arr}\n")

#Returns the flattened array(1D)
arr = arr.ravel()
print(f"Ravel \n{arr}\n")

Arange 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]

Reshape 
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]

Ravel 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]



In [5]:
x = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 1, 0]
]

ar = np.array(x)
print(f"The matrix X is : \n{ar}\n")

#Max(returns actual value)
print(f"MAX : {ar.max()}\n")

#Min(returns actual value)
print(f"MIN : {ar.min()}\n")

#Sum of all elements
print(f"Sum of all elements : {ar.sum()}\n")

#Sum of elements for axis = 0
print(f"Sum of axis = 0 : {ar.sum(axis = 0)}\n")

#Sum of elements for axis = 1
print(f"Sum of axis = 1 : {ar.sum(axis = 1)}\n")

#Transpose of a matrix
print(f"Transpose : \n{ar.T}\n")

#Returns a flattened array
print("ar.flat :")
for item in ar.flat:
    print(item)

#Number of dimensions
print(f"\nNumber of dimensions : {ar.ndim}\n")

#Size of array
print(f"Size of array : {ar.size}\n")

#Bytes consumed
print(f"Bytes consumed : {ar.nbytes}\n")

#"argmin" for 2D array
print(f"argmin for 2D array : {ar.argmin()}\n")

#"argmax for 2D array"
print(f"argmax for 2D array : {ar.argmax()}\n")

#argmax for axis = 0
print(f"argmax for axis = 0 : {ar.argmax(axis = 0)}\n")

#argmax for axis = 1
print(f"argmax for axis = 1 : {ar.argmax(axis = 1)}\n")

#ravel(flatten the 2D array)
print(f"ravel : \n{ar.ravel()}\n")

#reshape to 9*1 array
print(f"3*3 array reshaped to 9*1 :\n{ar.reshape(9,1)}")

The matrix X is : 
[[1 2 3]
 [4 5 6]
 [7 1 0]]

MAX : 7

MIN : 0

Sum of all elements : 29

Sum of axis = 0 : [12  8  9]

Sum of axis = 1 : [ 6 15  8]

Transpose : 
[[1 4 7]
 [2 5 1]
 [3 6 0]]

ar.flat :
1
2
3
4
5
6
7
1
0

Number of dimensions : 2

Size of array : 9

Bytes consumed : 72

argmin for 2D array : 8

argmax for 2D array : 6

argmax for axis = 0 : [2 1 1]

argmax for axis = 1 : [2 2 0]

ravel : 
[1 2 3 4 5 6 7 1 0]

3*3 array reshaped to 9*1 :
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [1]
 [0]]


In [6]:
#Matrix Operations

ar1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 1, 0]
])

ar2 = np.array([
    [1, 2, 1],
    [4, 0, 6],
    [8, 1, 0]
])

#Sum of metrices
print(f"Sum of metrices : \n{ar1 + ar2}\n")

#Multiplication of metrices
print(f"Multiplication of metrices : \n{ar1 * ar2}\n")

#element-wise sqrt
print(f"Element-wise sqrt : \n{np.sqrt(ar1)}\n")

Sum of metrices : 
[[ 2  4  4]
 [ 8  5 12]
 [15  2  0]]

Multiplication of metrices : 
[[ 1  4  3]
 [16  0 36]
 [56  1  0]]

Element-wise sqrt : 
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 1.         0.        ]]



In [7]:
#Searching in the 2D array

#make pairs using each array
#(1, 0), (1, 1), (1, 2), (2, 0)
print(f"INDICES of nos > 3 in ar1 : \n{np.where(ar1 > 3)}\n")

print(f"{type(np.where(ar1 > 3))}\n")

#count non-zero elements in ar1
print(f"no of non-zero elements : {np.count_nonzero(ar1)}\n")

#returns a tuple for each axis
print(f"non-zero elements : \n{np.nonzero(ar1)}\n")

INDICES of nos > 3 in ar1 : 
(array([1, 1, 1, 2]), array([0, 1, 2, 0]))

<class 'tuple'>

no of non-zero elements : 8

non-zero elements : 
(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))



In [8]:
#Storage Efficient
import sys

py_ar = [0, 55, 14, 2]
np_ar = np.array(py_ar)

print(f"storage consumed by py_ar : {sys.getsizeof(1) * len(py_ar)}")
print(f"storage consumed by np_ar : {np_ar.itemsize * np_ar.size}")

storage consumed by py_ar : 112
storage consumed by np_ar : 32
